// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdjecAOfT7dobrIGeTNsZlQhDYEfZkrqE',
    appId: '1:684648449179:web:992d323e40baa5033db23e',
    messagingSenderId: '684648449179',
    projectId: 'campus-sync-35972',
    authDomain: 'campus-sync-35972.firebaseapp.com',
    storageBucket: 'campus-sync-35972.appspot.com',
    measurementId: 'G-FYZPFYERFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAehRemr4-gFnWepSBLjEoHEjzppjjHvbQ',
    appId: '1:684648449179:android:92533a5e7c81b5383db23e',
    messagingSenderId: '684648449179',
    projectId: 'campus-sync-35972',
    storageBucket: 'campus-sync-35972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCciAIUPC1EOSTpBcFhtqeGoT4OoBDcKrU',
    appId: '1:684648449179:ios:4fac9a4cc924dbc93db23e',
    messagingSenderId: '684648449179',
    projectId: 'campus-sync-35972',
    storageBucket: 'campus-sync-35972.appspot.com',
    iosBundleId: 'com.example.campusSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCciAIUPC1EOSTpBcFhtqeGoT4OoBDcKrU',
    appId: '1:684648449179:ios:b814d1b6d436656d3db23e',
    messagingSenderId: '684648449179',
    projectId: 'campus-sync-35972',
    storageBucket: 'campus-sync-35972.appspot.com',
    iosBundleId: 'com.example.campusSync.RunnerTests',
  );
}
